site_name: Py Env Studio
site_url: https://py-env-studio.readthedocs.io
repo_url: https://github.com/pyenvstudio/py-env-studio
repo_name: pyenvstudio/py-env-studio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: cyan
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - Features: features.md
  - CLI Reference: cli.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings
