"""Data models for template definitions and project generation."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


@dataclass(frozen=True)
class TemplateFile:
    """One file generated by a template."""

    path: str
    content: str
    condition_key: Optional[str] = None


@dataclass(frozen=True)
class TemplateSpec:
    """Declarative template specification."""

    id: str
    name: str
    version: str
    description: str
    supported_python_versions: List[str]
    min_python: str
    architecture: str
    style: str
    included_tooling: List[str]
    runtime_dependencies: List[str]
    dev_dependencies: List[str]
    structure_preview: List[str]
    files: List[TemplateFile]
    default_license: str = "MIT"
    source: str = "built-in"
    category: str = "General"
    author: Optional[str] = None
    variable_style: str = "format"


@dataclass
class TemplateCreationRequest:
    """User-provided template variables and project creation options."""

    template_id: str
    project_name: str
    project_location: str
    python_version: str
    create_virtual_environment: bool
    initialize_git: bool
    package_name: Optional[str] = None
    cli_command_name: Optional[str] = None
    author: Optional[str] = None
    license_name: Optional[str] = None
    install_dev_dependencies: bool = True


@dataclass
class TemplateCreationResult:
    """Outcome of template generation."""

    template_id: str
    project_path: Path
    generated_files: List[Path] = field(default_factory=list)
    created_environment_name: Optional[str] = None
    installed_dependencies: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, str] = field(default_factory=dict)
