name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger when you create a GitHub Release

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "version=${TAG_NAME#v}" >> $GITHUB_OUTPUT

      - name: Update pyproject.toml version and config.ini
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml
          echo "Updated pyproject.toml to version $VERSION"
          sed -i "/^\[project\]/,/^\[/{s/^version *= *.*/version = ${VERSION}/}" py_env_studio/config.ini
          echo "✅ Updated config.ini to version $VERSION"

      - name: Install build tools
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
