name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "version=${TAG_NAME#v}" >> $GITHUB_OUTPUT

      - name: Update pyproject.toml version and config.ini
        run: |
          VERSION=${{ steps.get_version.outputs.version }}

          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml

          sed -i "/^\[project\]/,/^\[/{s/^version *= *.*/version = ${VERSION}/}" py_env_studio/config.ini

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1